postgres:
  image: postgres
  environment:
    - POSTGRES_USER=lemons
    - POSTGRES_PASSWORD=lemons
  ports:
    - 5432:5432

elasticsearch:
  image: elasticsearch
  ports:
    - 9200:9200
    - 9300:9300
