postgres:
  image: postgres
  environment:
    - POSTGRES_USER=lemons
    - POSTGRES_PASSWORD=lemons
  ports:
    - 5432:5432

elasticsearch:
  image: elasticsearch
  ports:
    - 9200:9200
    - 9300:9300

web:
  build: .
  dockerfile: Dockerfile-dev
  command: django-admin.py runserver 0.0.0.0:8000
  volumes:
    - .:/app
  ports:
    - "8000:8000"
  links:
    - postgres
    - elasticsearch
